import fs from "fs";
import matter from "gray-matter";
// import { Head } from "next/document";
import Link from "next/link";
import path from "path";
import Banner from "../components/Banner";
import { postFilePaths, POSTS_PATH } from "../utils/mdxUtils";

export default function Index({ posts }) {
  return (
    <>
      {/* <Head>
        <title>Pom's techlog, journey in adventureland</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
 */}
      <Banner />

      <main>
        <p>
          <Link href="/post-page">
            <a>Go to post page</a>
          </Link>
        </p>

        <p>
          Click the link below to navigate to a page generated by{" "}
          <code>next-mdx-remote</code>.
        </p>
        <ul>
          {posts.map((post) => (
            <li key={post.filePath}>
              <Link
                as={`/posts/${post.filePath.replace(/\.mdx?$/, "")}`}
                href={`/posts/[slug]`}
              >
                <a>{post.data.title}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
      <footer>
        <p>
          Made with&nbsp;
          <span role="img" aria-label="heart">
            ❤️
          </span>
          &nbsp;in 2021
        </p>
      </footer>
    </>
  );
}

export function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    const { content, data } = matter(source);

    return {
      content,
      data,
      filePath,
    };
  });

  return { props: { posts } };
}
